Repository DOME-Marketplace/access-node, pull requests merged in 2024-11, with the labels that each got.

#44 docs(image): update dome crypto generator example image
  doc/dome-key-generator-example.png
Labels: documentation

#39 Update tmf and fix tests
  .github/workflows/test.yaml
  charts/access-node/Chart.yaml
  charts/access-node/README.md
  charts/access-node/values.yaml
  it/charts/infra/access-node-list/Chart.yaml
  it/charts/infra/access-node-list/templates/cm.yaml
  it/charts/infra/access-node-list/templates/deployment.yaml
  it/charts/infra/access-node-list/templates/service.yaml
  it/charts/infra/access-node-list/values.yaml
  it/charts/infra/blockchain-testnode/templates/account-registration-cm.yaml
  it/charts/infra/blockchain-testnode/templates/contract-deploy.yaml
  it/charts/infra/blockchain-testnode/templates/deployment.yaml
  it/charts/infra/blockchain-testnode/values.yaml
  it/consumer-values.yaml
  it/consumer/values.yaml
  it/kustomization.yaml
  it/kustomize.sh
  it/pom.xml
  it/pr.yaml
  it/provider-values.yaml
  it/provider/values.yaml
Labels: minor

#48 update desmos
  README.md
  charts/access-node/Chart.yaml
  charts/access-node/README.md
  charts/access-node/values.yaml
Labels: patch
